# We still want to verify the cluster is up beforehand here

- name: Wait for cluster operator api call to be successfull
  k8s_info:
    api_version: v1
    kind: ClusterOperator
  register: reg_ocp_co
  ignore_errors: true
  when: not debug_json | bool
  until:
    - reg_ocp_co.rc is not defined
  retries: 10 # wait for 5 minutes max
  delay: 30

#TODO: Check version number here as well
- name: Verify that cluster finished the upgrade
  k8s_info:
    api_version: v1
    kind: ClusterVersion
  register: reg_ocp_version
  vars:
    progressing_query: "resources[0].status.conditions[?type=='Progressing'].status"
    progressing: "{{ reg_ocp_version | json_query(progressing_query) | flatten | unique }}"
  when: not debug_json | bool
  until:
    - reg_ocp_version.resources is defined
    - progressing == ['False']
  retries: 10 # wait for 5 minutes max
  delay: 30
