---
# - name: Verify openshift cluster is ready for upgrade
#   hosts: localhost
#   vars:
#     debug_json: false
#   roles:
#     - pre-upgrade-check
# 
# - name: Gather relevant openshift cluster information
#   hosts: localhost
#   vars:
#     debug_json: false
#   roles:
#   - gather-cluster-info
# 
# - name: Upgrade cluster based on user input
#   hosts: localhost
#   vars:
#     upgrade: true
#   vars_prompt:
#   - name: "upgrade_version"
#     prompt: "Which version would you like to upgrade to?"
#     private: no
#   roles:
#   - upgrade-cluster
# 
- name: Verify cluster health after upgrade has completed
  hosts: localhost
  vars:
    debug_json: false
  roles:
    - post-upgrade-check

  post_tasks:
    - debug:
        var: reg_ocp_version
