---
- name: Verify openshift cluster is ready for upgrade
  hosts: localhost
  vars:
    debug_json: false
  tasks:
    - block:
      - name: Check cluster prior to upgrade
        include_role:
          name: pre-upgrade-check
      - name: Cluster health check
        include_role:
          name: cluster-health-check
      rescue:
      - include_role:
          name: slack-notification
        vars:
          failed: true

- name: Ask user whether or not they want to perform a Y stream update
  hosts: localhost
  vars_prompt:
  - name: "y_up"
    prompt: "Would you like to perform a Y stream update? This will update the cluster to the latest Z stream update before providing versions, which may take up to an hour. Type <yes> or <no>."
    private: no
  vars:
    upgrade_version: latest
    upgrade: true
    debug_json: false
  tasks:
    - set_fact:
        y_update: "{{y_up}}"
    - block:
      - name: Upgrade cluster to latest Z stream
        include_role:
          name: upgrade-cluster
        when: y_update | bool
      - name: Check cluster health after Z stream updates
        include_role:
          name: cluster-health-check
        when: y_update | bool
        #This script is written for OCP 4.3, which is why I'm doing this - making this generic is awkward in ansible
      - name: Patch cluster for major version updates
        command: oc patch clusterversion version --type="merge" -p '{"spec":{"channel":"stable-4.4"}}'
        when: y_update | bool
      rescue:
      - include_role:
          name: slack-notification
        vars:
          failed: true

- name: Provide cluster upgrade paths
  hosts: localhost
  tasks: 
    - block:
      - name: Get the information on all possible upgrade paths
        command: oc adm upgrade
        register: raw_upgrade_info                                                                                                                                                                                       # The result of the upgrade command does not have nicely formatted json, so this is the quick and dirty way to display it
      - name: Display upgrade information
        debug:
          msg: "{{raw_upgrade_info | json_query(\"stdout_lines\") | flatten | unique}}"
      rescue:
      - include_role:
          name: slack-notification
        vars:
          failed: true

- name: Upgrade cluster and verify status after upgrade has completed
  hosts: localhost
  vars_prompt:
  - name: "upgrade_version"
    prompt: "Which version of OpenShift do you want to upgrade to?"
    private: no
  vars:
    debug_json: false
    upgrade: true
  tasks:
    - block:
      - name: Upgrade cluster to "{{upgrade_version}}"
        include_role:
          name: upgrade-cluster
      - name: Check that everything is the correct cluster version
        include_role:
          name: post-upgrade-check
      - name: Verify Cluster health
        include_role:
          name: cluster-health-check
      - name: Send success slack message
        include_role:
          name: slack-notification
        vars:
          failed: false
      rescue:
      - include_role:
          name: slack-notification
        vars:
          failed: true
