---
- name: Verify openshift cluster is ready for upgrade
  hosts: localhost
  vars:
    debug_json: true
  tasks:
  - name: Check cluster prior to upgrade
    include_role:
      name: pre-upgrade-check
  - name: Cluster health check
    include_role:
      name: cluster-health-check
  - name: Provide cluster upgrade paths
    include_role:
      name: gather-cluster-info

- name: Upgrade cluster and verify status after upgrade has completed
  hosts: localhost
  vars_prompt:
  - name: "upgrade_version"
    prompt: "Which version of OpenShift would you like ot upgrade to?"
    private: no
  vars:
    debug_json: false
    upgrade: true
  tasks:
  - name: Upgrade cluster
    include_role:
      name: upgrade-cluster
  - name: Check that everything is the correct cluster version
    include_role:
      name: post-upgrade-check
  - name: Verify Cluster health
    include_role:
      name: cluster-health-check
  - name: Send slack notification
    include_role:
      name: slack-notification
    vars:
     - success: true
