- name: Debug input version number
  debug:
    msg: "{{upgrade_version}}"

- name: Upgrade to latest Z stream
  command: oc adm upgrade --to-latest=true
  when:
   - upgrade | bool
   - y_update | bool
  register: output

- meta: end_play
  when: "'Cluster is already at the latest available version'" in output

- name: Perform the selected upgrade
  command: oc adm upgrade --to="{{upgrade_version}}"
  when: 
   - upgrade | bool
   - not y_update | bool

- name: Make sure cluster starts the upgrade process
  k8s_info:
    api_version: v1
    kind: ClusterVersion
  register: reg_ocp_version
  vars:
    progressing_query: "resources[0].status.conditions[?type=='Progressing'].status"
    progressing: "{{ reg_ocp_version | json_query(progressing_query) | flatten | unique }}"
  when: upgrade | bool
  until:
    - reg_ocp_version.resources is defined
    - progressing == ['True']
  retries: 10 # wait for 5 minutes max
  delay: 30
